[package]
name = "rayql-wasm"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
rayql-engine.workspace = true
wasm-bindgen.workspace = true
