[package]
name = "rayql-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
rayql-engine.workspace = true
wasm-bindgen.workspace = true
